djangoProject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views
app_name="polls"

urlpatterns=[
    path('',views.question_list,name='question_list'),
    path('<int:question_id>/', views.question_detail, name='question_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from projekcik import views

urlpatterns = [
    path('',views.home_view),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls',namespace='polls'))
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    type = models.BooleanField('pytanie zamkniete', default=True)
    def __str__(self):
        return self.question_text

class Answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    user_answer = models.CharField(default="Empty Answer", max_length=100)
    def __str__(self):
        return self.user_answer

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404

from .models import Question

def question_list(request):
    questions = Question.objects.filter(id=1)
    return render(request,'polls/question_list.html',{'questions':questions})
# Create your views here.

def question_detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/question_detail.html', {'question': question})

project/views.py
from django.shortcuts import render, get_object_or_404

def home_view(request):
    return render(request,'polls/home.html')

templates/polls/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <a href="{% url 'polls:question_list' %}">pytania</a>
    <br>
    {% if user.is_authenticated %}
        Witaj {{ user }}!
        {% else %}
        Nie jeśtes zalogowany.

    {% endif %}

</body>
</html>

templates/polls/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ STATIC_URL }}/styles.css" />
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/styles.css' %}" />
</head>
<body>
    <div class="mainbox infobox">
        <h1>{{ question.question_text }}</h1>
        <ul>
        {% for choice in question.choice_set.all %}
            <li><p>{{ choice.choice_text }} - {{ choice.votes }}</p></li>
        {% endfor %}
        {% for answer in question.answer_set.all %}
                <li>{{ answer.user_answer }}</li>
        {% endfor %}
        </ul>
    </div>
</body>
</html>

templates/polls/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/styles.css' %}" />

</head>
<body>
 <div>
    <table class="mainbox">
    <tr>
        <th>ID Pytania</th>
        <th>Tresc</th>
        <th>Data</th>
        <th>Pytanie Zamkniete</th>
    </tr>
     {% for question in questions %}
         <tr>
            <td>{{ question.id }}</td>
            <td><a href="{% url 'polls:question_detail' question.id %}">{{ question.question_text }}</a></td>
            <td>{{ question.pub_date }}</td>
            <td> {{ question.type }}</td>
        </tr>
     {% endfor %}
    </table>
 </div>
</body>
</html>